// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef layout_h
#define layout_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern void send_medical_data(Fl_Button*, void*);
#include <FL/Fl_Table.H>
Fl_Double_Window* make_window();

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1364, 190);
    w = o; if (w) {/* empty */}
    o->box(FL_EMBOSSED_BOX);
    { Fl_Button* o = new Fl_Button(122, 270, 100, 35, "Send");
      o->tooltip("Send selected files for processing");
      o->box(FL_ENGRAVED_BOX);
      o->shortcut(0x40073);
      o->callback((Fl_Callback*)send_medical_data);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  { Fl_Double_Window* o = new Fl_Double_Window(1364, 190);
    w = o; if (w) {/* empty */}
    { Fl_Table* o = new Fl_Table(0, 0, 465, 745);
      { Fl_Table* o = new Fl_Table(60, 25, 405, 720);
        o->end();
      } // Fl_Table* o
      o->end();
    } // Fl_Table* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
#endif
