#!/bin/sh

# reliable password fuzzy searcher

cd "${PASSWORD_STORE_DIR}" || exit 1

selection="$(find -L . -name '*.gpg' | sed 's/.gpg$//g' | ${FUZZER})"

test -z "${selection}" || pass ${1} "${selection}"

