#!/bin/sh

# rssr - rss reader

[ -z "$RSSR_FUZZY_SEARCHER" ] && RSSR_FUZZY_SEARCHER=fzy
[ -z "$FEEDS_PATH" ] && FEEDS_PATH="${HOME}/.sfeed/feeds"
[ -z "$OPEN_PROGRAM" ] && OPEN_PROGRAM=open

test -z "$RSSR_FUZZY_SEARCHER" && ( echo "RSSR_FUZZY_SEARCHER needs to be set" && exit 1 )

cd "$FEEDS_PATH" || (echo "FEEDS_PATH: $FEEDS_PATH does not exist" && exit 1)

website="$(ls | $RSSR_FUZZY_SEARCHER)"

[ -n "$website" ] && link=$(cat "$website" | cut -f3 | $RSSR_FUZZY_SEARCHER)

[ -n "$link" ] && "$OPEN_PROGRAM"  "$link"

