// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "autodoc.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(600, 275);
    w = o; if (w) {/* empty */}
    { new Fl_Button(240, 235, 60, 25, "Send");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(305, 10, 285, 250);
      { Fl_Table* o = new Fl_Table(330, 35, 260, 225);
        o->end();
      } // Fl_Table* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(25, 25, 280, 200);
      o->end();
    } // Fl_Group* o
    { new Fl_Input(40, 235, 185, 25);
    } // Fl_Input* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
