// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef autodoc_h
#define autodoc_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Input.H>
Fl_Double_Window* make_window();
#endif
